-- Minimal schema for the admin dashboard (static site + supabase-js in browser).
-- Run this in Supabase SQL Editor for your project.
--
-- Security note:
-- If you keep the admin dashboard publicly reachable and use the anon key,
-- you MUST protect these tables with RLS + auth. This schema does not add policies.

create table if not exists public.profile (
  id bigint primary key,
  full_name text,
  headline text,
  bio text,
  hero_title text,
  hero_subtitle text,
  summary_text text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.experience (
  id bigint generated by default as identity primary key,
  company text not null,
  role text not null,
  start_date date,
  end_date date,
  description text,
  is_current boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.education (
  id bigint generated by default as identity primary key,
  degree text,
  school text,
  description text,
  created_at timestamptz not null default now()
);

create table if not exists public.credentials (
  id bigint generated by default as identity primary key,
  kind text not null check (kind in ('certification', 'course')),
  title text not null,
  issuer text,
  year integer,
  category text,
  note text,
  proof_image_url text,
  proof_url text,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

create unique index if not exists credentials_kind_title_key
on public.credentials (kind, title);

create table if not exists public.skills (
  id bigint generated by default as identity primary key,
  category text not null check (category in ('hero', 'main')),
  name text not null,
  description text,
  created_at timestamptz not null default now()
);

create table if not exists public.blog_posts (
  id bigint generated by default as identity primary key,
  slug text not null,
  title text not null,
  excerpt text,
  cover_image_url text,
  is_published boolean not null default true,
  published_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists blog_posts_slug_key
on public.blog_posts (slug);

create table if not exists public.blog_chapters (
  id bigint generated by default as identity primary key,
  post_id bigint not null references public.blog_posts(id) on delete cascade,
  title text not null,
  body text,
  image_url text,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists blog_chapters_post_sort_key
on public.blog_chapters (post_id, sort_order);

-- Seed demo content (safe to re-run).
with post_row as (
  insert into public.blog_posts (slug, title, excerpt, cover_image_url, is_published, published_at)
  values (
    'first-post',
    'First Post (Demo)',
    'Generic post to test the blog end-to-end: list view, post detail with chapters and images, and editing from the dashboard.',
    'assets/images/blog/cover-generic.png',
    true,
    now()
  )
  on conflict (slug) do update set
    title = excluded.title,
    excerpt = excluded.excerpt,
    cover_image_url = excluded.cover_image_url,
    is_published = excluded.is_published
  returning id
)
insert into public.blog_chapters (post_id, sort_order, title, body, image_url)
select
  post_row.id,
  v.sort_order,
  v.title,
  v.body,
  v.image_url
from post_row
cross join (
  values
    (0, 'Chapter 1: Structure', E'This is a generic chapter.\n\nIt includes a text block and an image area.', 'assets/images/blog/chapter-1.png'),
    (1, 'Chapter 2: Images', E'Images can be local paths (assets/...) or public URLs from Supabase Storage.\n\nFrom the dashboard you can upload an image and save its URL on the chapter.', 'assets/images/blog/chapter-2.png'),
    (2, 'Chapter 3: Publishing', E'You can publish the post or keep it as a draft.\n\nVisitors only see published posts.', 'assets/images/blog/chapter-3.png')
) as v(sort_order, title, body, image_url)
on conflict (post_id, sort_order) do update set
  title = excluded.title,
  body = excluded.body,
  image_url = excluded.image_url;

-- DEV/UNSAFE: grants to use anon key from a public webpage.
-- Prefer enabling RLS + auth for any real deployment.
grant usage on schema public to anon, authenticated;
grant select, insert, update, delete on public.profile to anon, authenticated;
grant select, insert, update, delete on public.experience to anon, authenticated;
grant select, insert, update, delete on public.education to anon, authenticated;
grant select, insert, update, delete on public.credentials to anon, authenticated;
grant select, insert, update, delete on public.skills to anon, authenticated;
grant select, insert, update, delete on public.blog_posts to anon, authenticated;
grant select, insert, update, delete on public.blog_chapters to anon, authenticated;
grant usage, select, update on all sequences in schema public to anon, authenticated;
