-- Minimal schema for the admin dashboard (static site + supabase-js in browser).
-- Run this in Supabase SQL Editor for your project.
--
-- Security note:
-- If you keep the admin dashboard publicly reachable and use the anon key,
-- you MUST protect these tables with RLS + auth. This schema does not add policies.

create table if not exists public.profile (
  id bigint primary key,
  full_name text,
  headline text,
  bio text,
  hero_title text,
  hero_subtitle text,
  summary_text text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.experience (
  id bigint generated by default as identity primary key,
  company text not null,
  role text not null,
  start_date date,
  end_date date,
  description text,
  is_current boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.education (
  id bigint generated by default as identity primary key,
  degree text,
  school text,
  description text,
  created_at timestamptz not null default now()
);

create table if not exists public.certifications (
  id bigint generated by default as identity primary key,
  name text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.credentials (
  id bigint generated by default as identity primary key,
  kind text not null check (kind in ('certification', 'course')),
  title text not null,
  issuer text,
  year integer,
  category text,
  note text,
  proof_image_url text,
  proof_url text,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

create unique index if not exists credentials_kind_title_key
on public.credentials (kind, title);

create table if not exists public.skills (
  id bigint generated by default as identity primary key,
  category text not null check (category in ('hero', 'main')),
  name text not null,
  description text,
  created_at timestamptz not null default now()
);

-- DEV/UNSAFE: grants to use anon key from a public webpage.
-- Prefer enabling RLS + auth for any real deployment.
grant usage on schema public to anon, authenticated;
grant select, insert, update, delete on public.profile to anon, authenticated;
grant select, insert, update, delete on public.experience to anon, authenticated;
grant select, insert, update, delete on public.education to anon, authenticated;
grant select, insert, update, delete on public.certifications to anon, authenticated;
grant select, insert, update, delete on public.credentials to anon, authenticated;
grant select, insert, update, delete on public.skills to anon, authenticated;
