-- ============================================================
-- Secure Supabase setup:
-- - Structured tables used by /admin/dashboard.html
-- - CMS HTML snapshots + media uploads for "WordPress-like" editing
-- - Public read, admin-only writes (by Auth email)
--
-- Steps:
-- 1) Create your Auth user in Dashboard (Authentication -> Users).
-- 2) Run this SQL in SQL Editor.
--
-- Notes:
-- - Do NOT ship your service_role key to the browser.
-- - This relies on RLS and requires the editor/admin to sign in.
-- ============================================================

-- ---------------------------
-- 0) Helpers
-- ---------------------------
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create or replace function public.is_admin()
returns boolean
language sql
stable
as $$
  select lower(coalesce(auth.jwt() ->> 'email', '')) = 'jreynoso111@gmail.com'
$$;

-- ---------------------------
-- 1) Structured content tables
-- ---------------------------
create table if not exists public.profile (
  id bigint primary key,
  full_name text,
  headline text,
  bio text,
  hero_title text,
  hero_subtitle text,
  summary_text text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

drop trigger if exists set_profile_updated_at on public.profile;
create trigger set_profile_updated_at
before update on public.profile
for each row execute function public.set_updated_at();

insert into public.profile (id) values (1)
on conflict (id) do nothing;

create table if not exists public.experience (
  id bigint generated by default as identity primary key,
  company text not null,
  role text not null,
  start_date date,
  end_date date,
  description text,
  is_current boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.education (
  id bigint generated by default as identity primary key,
  degree text,
  school text,
  description text,
  created_at timestamptz not null default now()
);

create table if not exists public.certifications (
  id bigint generated by default as identity primary key,
  name text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.skills (
  id bigint generated by default as identity primary key,
  category text not null check (category in ('hero', 'main')),
  name text not null,
  description text,
  created_at timestamptz not null default now()
);

-- ---------------------------
-- 2) CMS HTML snapshots
-- ---------------------------
create table if not exists public.cms_pages (
  path text primary key,
  html text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

drop trigger if exists set_cms_pages_updated_at on public.cms_pages;
create trigger set_cms_pages_updated_at
before update on public.cms_pages
for each row execute function public.set_updated_at();

-- ---------------------------
-- 2b) Projects cards (used by /pages/projects.html)
-- ---------------------------
create table if not exists public.projects (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  href text not null,
  image_url text,
  sort_order integer not null default 0,
  is_published boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

drop trigger if exists set_projects_updated_at on public.projects;
create trigger set_projects_updated_at
before update on public.projects
for each row execute function public.set_updated_at();

-- ---------------------------
-- 3) Grants (RLS still applies)
-- ---------------------------
grant usage on schema public to anon, authenticated;

grant select on public.profile to anon, authenticated;
grant select on public.experience to anon, authenticated;
grant select on public.education to anon, authenticated;
grant select on public.certifications to anon, authenticated;
grant select on public.skills to anon, authenticated;
grant select on public.cms_pages to anon, authenticated;
grant select on public.projects to anon, authenticated;

grant insert, update, delete on public.profile to authenticated;
grant insert, update, delete on public.experience to authenticated;
grant insert, update, delete on public.education to authenticated;
grant insert, update, delete on public.certifications to authenticated;
grant insert, update, delete on public.skills to authenticated;
grant insert, update, delete on public.cms_pages to authenticated;
grant insert, update, delete on public.projects to authenticated;

grant usage, select, update on all sequences in schema public to authenticated;

-- ---------------------------
-- 4) RLS policies
-- Public read, admin-only writes
-- ---------------------------
alter table public.profile enable row level security;
alter table public.experience enable row level security;
alter table public.education enable row level security;
alter table public.certifications enable row level security;
alter table public.skills enable row level security;
alter table public.cms_pages enable row level security;
alter table public.projects enable row level security;

-- Public read
drop policy if exists profile_public_read on public.profile;
create policy profile_public_read on public.profile
for select to anon, authenticated
using (true);

drop policy if exists experience_public_read on public.experience;
create policy experience_public_read on public.experience
for select to anon, authenticated
using (true);

drop policy if exists education_public_read on public.education;
create policy education_public_read on public.education
for select to anon, authenticated
using (true);

drop policy if exists certifications_public_read on public.certifications;
create policy certifications_public_read on public.certifications
for select to anon, authenticated
using (true);

drop policy if exists skills_public_read on public.skills;
create policy skills_public_read on public.skills
for select to anon, authenticated
using (true);

drop policy if exists cms_pages_public_read on public.cms_pages;
create policy cms_pages_public_read on public.cms_pages
for select to anon, authenticated
using (true);

drop policy if exists projects_public_read on public.projects;
create policy projects_public_read on public.projects
for select to anon, authenticated
using (is_published = true);

drop policy if exists projects_admin_read on public.projects;
create policy projects_admin_read on public.projects
for select to authenticated
using (public.is_admin());

-- Admin writes (authenticated + email match)
drop policy if exists profile_admin_insert on public.profile;
create policy profile_admin_insert on public.profile
for insert to authenticated
with check (public.is_admin());

drop policy if exists profile_admin_update on public.profile;
create policy profile_admin_update on public.profile
for update to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists profile_admin_delete on public.profile;
create policy profile_admin_delete on public.profile
for delete to authenticated
using (public.is_admin());

drop policy if exists experience_admin_insert on public.experience;
create policy experience_admin_insert on public.experience
for insert to authenticated
with check (public.is_admin());

drop policy if exists experience_admin_update on public.experience;
create policy experience_admin_update on public.experience
for update to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists experience_admin_delete on public.experience;
create policy experience_admin_delete on public.experience
for delete to authenticated
using (public.is_admin());

drop policy if exists education_admin_insert on public.education;
create policy education_admin_insert on public.education
for insert to authenticated
with check (public.is_admin());

drop policy if exists education_admin_update on public.education;
create policy education_admin_update on public.education
for update to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists education_admin_delete on public.education;
create policy education_admin_delete on public.education
for delete to authenticated
using (public.is_admin());

drop policy if exists certifications_admin_insert on public.certifications;
create policy certifications_admin_insert on public.certifications
for insert to authenticated
with check (public.is_admin());

drop policy if exists certifications_admin_update on public.certifications;
create policy certifications_admin_update on public.certifications
for update to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists certifications_admin_delete on public.certifications;
create policy certifications_admin_delete on public.certifications
for delete to authenticated
using (public.is_admin());

drop policy if exists skills_admin_insert on public.skills;
create policy skills_admin_insert on public.skills
for insert to authenticated
with check (public.is_admin());

drop policy if exists skills_admin_update on public.skills;
create policy skills_admin_update on public.skills
for update to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists skills_admin_delete on public.skills;
create policy skills_admin_delete on public.skills
for delete to authenticated
using (public.is_admin());

drop policy if exists cms_pages_admin_insert on public.cms_pages;
create policy cms_pages_admin_insert on public.cms_pages
for insert to authenticated
with check (public.is_admin());

drop policy if exists cms_pages_admin_update on public.cms_pages;
create policy cms_pages_admin_update on public.cms_pages
for update to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists cms_pages_admin_delete on public.cms_pages;
create policy cms_pages_admin_delete on public.cms_pages
for delete to authenticated
using (public.is_admin());

drop policy if exists projects_admin_insert on public.projects;
create policy projects_admin_insert on public.projects
for insert to authenticated
with check (public.is_admin());

drop policy if exists projects_admin_update on public.projects;
create policy projects_admin_update on public.projects
for update to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists projects_admin_delete on public.projects;
create policy projects_admin_delete on public.projects
for delete to authenticated
using (public.is_admin());

-- ---------------------------
-- 5) Storage bucket
-- ---------------------------
-- Bucket (public read URLs via /object/public).
insert into storage.buckets (id, name, public)
values ('resume-cms', 'resume-cms', true)
on conflict (id) do update set public = excluded.public;

-- NOTE: storage.objects is owned by supabase_storage_admin, so policies are best managed
-- via the Supabase Dashboard (Storage -> Policies), OR upload via an Edge Function that
-- uses the service role key (recommended for static hosting).
