-- ============================================================
-- Secure Supabase setup:
-- - Structured tables used by /admin/dashboard.html
-- - CMS HTML snapshots + media uploads for "WordPress-like" editing
-- - Public read, admin-only writes (by Auth email)
--
-- Steps:
-- 1) Create your Auth user in Dashboard (Authentication -> Users).
-- 2) Run this SQL in SQL Editor.
--
-- Notes:
-- - Do NOT ship your service_role key to the browser.
-- - This relies on RLS and requires the editor/admin to sign in.
-- ============================================================

-- ---------------------------
-- 0) Helpers
-- ---------------------------
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create or replace function public.is_admin()
returns boolean
language sql
stable
as $$
  select lower(coalesce(auth.jwt() ->> 'email', '')) = 'jreynoso111@gmail.com'
$$;

-- ---------------------------
-- 1) Structured content tables
-- ---------------------------
create table if not exists public.profile (
  id bigint primary key,
  full_name text,
  headline text,
  bio text,
  hero_title text,
  hero_subtitle text,
  summary_text text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

drop trigger if exists set_profile_updated_at on public.profile;
create trigger set_profile_updated_at
before update on public.profile
for each row execute function public.set_updated_at();

insert into public.profile (id) values (1)
on conflict (id) do nothing;

create table if not exists public.experience (
  id bigint generated by default as identity primary key,
  company text not null,
  role text not null,
  start_date date,
  end_date date,
  description text,
  is_current boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.education (
  id bigint generated by default as identity primary key,
  degree text,
  school text,
  description text,
  created_at timestamptz not null default now()
);

create table if not exists public.credentials (
  id bigint generated by default as identity primary key,
  kind text not null check (kind in ('certification', 'course')),
  title text not null,
  issuer text,
  year integer,
  category text,
  note text,
  proof_image_url text,
  proof_url text,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

drop trigger if exists set_credentials_updated_at on public.credentials;
create trigger set_credentials_updated_at
before update on public.credentials
for each row execute function public.set_updated_at();

create unique index if not exists credentials_kind_title_key
on public.credentials (kind, title);

-- Seed items (safe to re-run).
insert into public.credentials (kind, title, issuer, year, category, note, proof_image_url, proof_url, sort_order)
values
  ('certification', 'Data Analysis & Data Visualization', 'Professional Training', null, 'Analytics', 'Credential focused on translating operational data into management reporting and clear visual insights.', null, null, 0),
  ('certification', 'Internal Auditor — ISO 9001:2015', 'ISO Quality Management', null, 'Quality', 'Internal auditor credential supporting structured process control, compliance checks, and corrective-action discipline.', null, null, 1),
  ('certification', 'Rail Systems Technical Training — SCADA', 'Rail Systems Operations', null, 'Rail Systems', 'Technical training supporting SCADA monitoring, incident response, and maintenance coordination in rail operations.', null, null, 2),
  ('certification', 'Rail Systems Technical Training — CCTV', 'Rail Systems Operations', null, 'Rail Systems', 'Technical training supporting CCTV operational readiness, troubleshooting workflows, and service continuity.', null, null, 3),
  ('certification', 'Rail Systems Technical Training — TETRA Radios', 'Rail Systems Operations', null, 'Rail Systems', 'Technical training supporting radio communications operations, fault triage, and field coordination discipline.', null, null, 4),
  ('certification', 'Rail Systems Technical Training — Access Control', 'Rail Systems Operations', null, 'Rail Systems', 'Technical training supporting access-control system reliability, monitoring, and incident response procedures.', null, null, 5),
  ('certification', 'Rail Systems Technical Training — Intrusion Detection', 'Rail Systems Operations', null, 'Rail Systems', 'Technical training supporting intrusion detection oversight, alarm workflows, and escalation coordination.', null, null, 6),
  ('certification', 'Rail Systems Technical Training — Telephony', 'Rail Systems Operations', null, 'Rail Systems', 'Technical training supporting telephony service continuity, troubleshooting routines, and operational readiness.', null, null, 7),
  ('certification', 'Rail Systems Technical Training — Axle Counters', 'Rail Systems Operations', null, 'Rail Systems', 'Technical training supporting axle counter systems, condition monitoring, and maintenance coordination.', null, null, 8),
  ('course', 'Big Data (training)', 'Professional Training', null, 'Analytics', 'Coursework in big-data concepts used to strengthen operational reporting, KPI governance, and decision support.', null, null, 9),
  ('course', 'Coursera (courses)', 'Coursera', null, 'Online Learning', 'Ongoing professional coursework supporting analytics, operations management, and technical upskilling.', null, null, 10),
  ('course', 'DataCamp (courses)', 'DataCamp', null, 'Analytics', 'Applied coursework in data tools and workflows supporting reporting automation and operational visibility.', null, null, 11),
  ('course', 'Infotep (courses)', 'INFOTEP', null, 'Workforce Training', 'Technical training supporting service operations discipline, systems maintenance, and organizational execution.', null, null, 12),
  ('course', 'SQL (training)', 'Professional Training', null, 'Data', 'Querying and data fundamentals applied to KPI dashboards, management reporting, and operational analysis.', null, null, 13),
  ('course', 'Power BI (training)', 'Professional Training', null, 'Reporting', 'Dashboard design and KPI storytelling used as management tools for accountability and execution reviews.', null, null, 14),
  ('course', 'Python (training)', 'Professional Training', null, 'Automation', 'Analytics and automation scripting supporting faster reporting cycles and cleaner operational insights.', null, null, 15),
  ('course', 'R (training)', 'Professional Training', null, 'Analytics', 'Statistical analysis and reporting workflows supporting data-backed operational decision-making.', null, null, 16),
  ('course', 'Project Management (coursework/training — not a certification)', 'Coursework / Training', null, 'Operations', 'Project execution fundamentals supporting maintenance planning, vendor coordination, and delivery discipline.', null, null, 17)
on conflict (kind, title) do nothing;

create table if not exists public.skills (
  id bigint generated by default as identity primary key,
  category text not null check (category in ('hero', 'main')),
  name text not null,
  description text,
  created_at timestamptz not null default now()
);

-- ---------------------------
-- 2) CMS HTML snapshots
-- ---------------------------
create table if not exists public.cms_pages (
  path text primary key,
  html text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

drop trigger if exists set_cms_pages_updated_at on public.cms_pages;
create trigger set_cms_pages_updated_at
before update on public.cms_pages
for each row execute function public.set_updated_at();

create table if not exists public.cms_change_log (
  id bigint generated by default as identity primary key,
  page_path text not null,
  change_reason text not null default 'publish',
  editor_email text,
  char_count integer,
  created_at timestamptz not null default now()
);

-- ---------------------------
-- 2b) Projects cards (used by /pages/projects.html)
-- ---------------------------
create table if not exists public.projects (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  href text not null,
  image_url text,
  sort_order integer not null default 0,
  is_published boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

drop trigger if exists set_projects_updated_at on public.projects;
create trigger set_projects_updated_at
before update on public.projects
for each row execute function public.set_updated_at();

-- ---------------------------
-- 2c) Blog posts + chapters (used by /pages/blog.html)
-- ---------------------------
create table if not exists public.blog_posts (
  id bigint generated by default as identity primary key,
  slug text not null,
  title text not null,
  excerpt text,
  cover_image_url text,
  is_published boolean not null default true,
  published_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

drop trigger if exists set_blog_posts_updated_at on public.blog_posts;
create trigger set_blog_posts_updated_at
before update on public.blog_posts
for each row execute function public.set_updated_at();

create unique index if not exists blog_posts_slug_key
on public.blog_posts (slug);

create table if not exists public.blog_chapters (
  id bigint generated by default as identity primary key,
  post_id bigint not null references public.blog_posts(id) on delete cascade,
  title text not null,
  body text,
  image_url text,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

drop trigger if exists set_blog_chapters_updated_at on public.blog_chapters;
create trigger set_blog_chapters_updated_at
before update on public.blog_chapters
for each row execute function public.set_updated_at();

create unique index if not exists blog_chapters_post_sort_key
on public.blog_chapters (post_id, sort_order);

create index if not exists blog_chapters_post_id_idx
on public.blog_chapters (post_id);

-- Seed demo content (safe to re-run).
with post_row as (
  insert into public.blog_posts (slug, title, excerpt, cover_image_url, is_published, published_at)
  values (
    'first-post',
    'First Post (Demo)',
    'Generic post to test the blog end-to-end: list view, post detail with chapters and images, and editing from the dashboard.',
    'assets/images/blog/cover-generic.png',
    true,
    now()
  )
  on conflict (slug) do update set
    title = excluded.title,
    excerpt = excluded.excerpt,
    cover_image_url = excluded.cover_image_url,
    is_published = excluded.is_published
  returning id
)
insert into public.blog_chapters (post_id, sort_order, title, body, image_url)
select
  post_row.id,
  v.sort_order,
  v.title,
  v.body,
  v.image_url
from post_row
cross join (
  values
    (0, 'Chapter 1: Structure', E'This is a generic chapter.\n\nIt includes a text block and an image area.', 'assets/images/blog/chapter-1.png'),
    (1, 'Chapter 2: Images', E'Images can be local paths (assets/...) or public URLs from Supabase Storage.\n\nFrom the dashboard you can upload an image and save its URL on the chapter.', 'assets/images/blog/chapter-2.png'),
    (2, 'Chapter 3: Publishing', E'You can publish the post or keep it as a draft.\n\nVisitors only see published posts.', 'assets/images/blog/chapter-3.png')
) as v(sort_order, title, body, image_url)
on conflict (post_id, sort_order) do update set
  title = excluded.title,
  body = excluded.body,
  image_url = excluded.image_url;

-- ---------------------------
-- 3) Grants (RLS still applies)
-- ---------------------------
grant usage on schema public to anon, authenticated;

grant select on public.profile to anon, authenticated;
grant select on public.experience to anon, authenticated;
grant select on public.education to anon, authenticated;
grant select on public.credentials to anon, authenticated;
grant select on public.skills to anon, authenticated;
grant select on public.cms_pages to anon, authenticated;
grant select on public.cms_change_log to anon, authenticated;
grant select on public.projects to anon, authenticated;
grant select on public.blog_posts to anon, authenticated;
grant select on public.blog_chapters to anon, authenticated;

grant insert, update, delete on public.profile to authenticated;
grant insert, update, delete on public.experience to authenticated;
grant insert, update, delete on public.education to authenticated;
grant insert, update, delete on public.credentials to authenticated;
grant insert, update, delete on public.skills to authenticated;
grant insert, update, delete on public.cms_pages to authenticated;
grant insert on public.cms_change_log to authenticated;
grant insert, update, delete on public.projects to authenticated;
grant insert, update, delete on public.blog_posts to authenticated;
grant insert, update, delete on public.blog_chapters to authenticated;

grant usage, select, update on all sequences in schema public to authenticated;

-- ---------------------------
-- 4) RLS policies
-- Public read, admin-only writes
-- ---------------------------
alter table public.profile enable row level security;
alter table public.experience enable row level security;
alter table public.education enable row level security;
alter table public.credentials enable row level security;
alter table public.skills enable row level security;
alter table public.cms_pages enable row level security;
alter table public.cms_change_log enable row level security;
alter table public.projects enable row level security;
alter table public.blog_posts enable row level security;
alter table public.blog_chapters enable row level security;

-- Public read
drop policy if exists profile_public_read on public.profile;
create policy profile_public_read on public.profile
for select to anon, authenticated
using (true);

drop policy if exists experience_public_read on public.experience;
create policy experience_public_read on public.experience
for select to anon, authenticated
using (true);

drop policy if exists education_public_read on public.education;
create policy education_public_read on public.education
for select to anon, authenticated
using (true);

drop policy if exists credentials_public_read on public.credentials;
create policy credentials_public_read on public.credentials
for select to anon, authenticated
using (true);

drop policy if exists skills_public_read on public.skills;
create policy skills_public_read on public.skills
for select to anon, authenticated
using (true);

drop policy if exists cms_pages_public_read on public.cms_pages;
create policy cms_pages_public_read on public.cms_pages
for select to anon, authenticated
using (true);

drop policy if exists cms_change_log_public_read on public.cms_change_log;
create policy cms_change_log_public_read on public.cms_change_log
for select to anon, authenticated
using (true);

drop policy if exists projects_public_read on public.projects;
create policy projects_public_read on public.projects
for select to anon, authenticated
using (is_published = true);

drop policy if exists projects_admin_read on public.projects;
create policy projects_admin_read on public.projects
for select to authenticated
using (public.is_admin());

drop policy if exists blog_posts_public_read on public.blog_posts;
create policy blog_posts_public_read on public.blog_posts
for select to anon, authenticated
using (is_published = true);

drop policy if exists blog_posts_admin_read on public.blog_posts;
create policy blog_posts_admin_read on public.blog_posts
for select to authenticated
using (public.is_admin());

drop policy if exists blog_chapters_public_read on public.blog_chapters;
create policy blog_chapters_public_read on public.blog_chapters
for select to anon, authenticated
using (
  exists (
    select 1
    from public.blog_posts p
    where p.id = blog_chapters.post_id
      and p.is_published = true
  )
);

drop policy if exists blog_chapters_admin_read on public.blog_chapters;
create policy blog_chapters_admin_read on public.blog_chapters
for select to authenticated
using (public.is_admin());

-- Admin writes (authenticated + email match)
drop policy if exists profile_admin_insert on public.profile;
create policy profile_admin_insert on public.profile
for insert to authenticated
with check (public.is_admin());

drop policy if exists profile_admin_update on public.profile;
create policy profile_admin_update on public.profile
for update to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists profile_admin_delete on public.profile;
create policy profile_admin_delete on public.profile
for delete to authenticated
using (public.is_admin());

drop policy if exists experience_admin_insert on public.experience;
create policy experience_admin_insert on public.experience
for insert to authenticated
with check (public.is_admin());

drop policy if exists experience_admin_update on public.experience;
create policy experience_admin_update on public.experience
for update to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists experience_admin_delete on public.experience;
create policy experience_admin_delete on public.experience
for delete to authenticated
using (public.is_admin());

drop policy if exists education_admin_insert on public.education;
create policy education_admin_insert on public.education
for insert to authenticated
with check (public.is_admin());

drop policy if exists education_admin_update on public.education;
create policy education_admin_update on public.education
for update to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists education_admin_delete on public.education;
create policy education_admin_delete on public.education
for delete to authenticated
using (public.is_admin());

drop policy if exists credentials_admin_insert on public.credentials;
create policy credentials_admin_insert on public.credentials
for insert to authenticated
with check (public.is_admin());

drop policy if exists credentials_admin_update on public.credentials;
create policy credentials_admin_update on public.credentials
for update to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists credentials_admin_delete on public.credentials;
create policy credentials_admin_delete on public.credentials
for delete to authenticated
using (public.is_admin());

drop policy if exists skills_admin_insert on public.skills;
create policy skills_admin_insert on public.skills
for insert to authenticated
with check (public.is_admin());

drop policy if exists skills_admin_update on public.skills;
create policy skills_admin_update on public.skills
for update to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists skills_admin_delete on public.skills;
create policy skills_admin_delete on public.skills
for delete to authenticated
using (public.is_admin());

drop policy if exists cms_pages_admin_insert on public.cms_pages;
create policy cms_pages_admin_insert on public.cms_pages
for insert to authenticated
with check (public.is_admin());

drop policy if exists cms_pages_admin_update on public.cms_pages;
create policy cms_pages_admin_update on public.cms_pages
for update to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists cms_pages_admin_delete on public.cms_pages;
create policy cms_pages_admin_delete on public.cms_pages
for delete to authenticated
using (public.is_admin());

drop policy if exists cms_change_log_admin_insert on public.cms_change_log;
create policy cms_change_log_admin_insert on public.cms_change_log
for insert to authenticated
with check (public.is_admin());

drop policy if exists projects_admin_insert on public.projects;
create policy projects_admin_insert on public.projects
for insert to authenticated
with check (public.is_admin());

drop policy if exists projects_admin_update on public.projects;
create policy projects_admin_update on public.projects
for update to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists projects_admin_delete on public.projects;
create policy projects_admin_delete on public.projects
for delete to authenticated
using (public.is_admin());

drop policy if exists blog_posts_admin_insert on public.blog_posts;
create policy blog_posts_admin_insert on public.blog_posts
for insert to authenticated
with check (public.is_admin());

drop policy if exists blog_posts_admin_update on public.blog_posts;
create policy blog_posts_admin_update on public.blog_posts
for update to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists blog_posts_admin_delete on public.blog_posts;
create policy blog_posts_admin_delete on public.blog_posts
for delete to authenticated
using (public.is_admin());

drop policy if exists blog_chapters_admin_insert on public.blog_chapters;
create policy blog_chapters_admin_insert on public.blog_chapters
for insert to authenticated
with check (public.is_admin());

drop policy if exists blog_chapters_admin_update on public.blog_chapters;
create policy blog_chapters_admin_update on public.blog_chapters
for update to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists blog_chapters_admin_delete on public.blog_chapters;
create policy blog_chapters_admin_delete on public.blog_chapters
for delete to authenticated
using (public.is_admin());

-- ---------------------------
-- 5) Storage bucket
-- ---------------------------
-- Bucket (public read URLs via /object/public).
insert into storage.buckets (id, name, public)
values ('resume-cms', 'resume-cms', true)
on conflict (id) do update set public = excluded.public;

-- NOTE: storage.objects is owned by supabase_storage_admin, so policies are best managed
-- via the Supabase Dashboard (Storage -> Policies), OR upload via an Edge Function that
-- uses the service role key (recommended for static hosting).
