#!/usr/bin/env python3
"""Pre-render crawlable blog pages and sitemap output from public blog data."""

from __future__ import annotations

import html
import json
import re
import subprocess
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from urllib.request import Request, urlopen


ROOT = Path(__file__).resolve().parents[1]
BLOG_INDEX_PATH = ROOT / "pages" / "blog.html"
BLOG_DETAIL_DIR = ROOT / "pages" / "blog"
SUPABASE_CONFIG_PATH = ROOT / "js" / "supabase-config.js"
LOCAL_BLOG_POSTS_PATH = ROOT / "js" / "blog-local-posts.js"
SITE_ORIGIN = "https://www.jreynoso.net"
GENERATED_MARKER = "<!-- Generated by scripts/prerender_blog.py. Do not edit directly. -->"
VALID_SLUG = re.compile(r"^[a-z0-9]+(?:-[a-z0-9]+)*$")


@dataclass(frozen=True)
class BlogPost:
    id: int
    slug: str
    title: str
    excerpt: str
    body: str
    cover_image_url: str
    published_at: str
    updated_at: str
    created_at: str


def read_public_config() -> tuple[str, str]:
    source = SUPABASE_CONFIG_PATH.read_text(encoding="utf-8")
    url_match = re.search(r"\burl:\s*['\"]([^'\"]+)['\"]", source)
    key_match = re.search(r"\banonKey:\s*['\"]([^'\"]+)['\"]", source)
    if not url_match or not key_match:
        raise RuntimeError("Supabase public URL or anon key was not found in js/supabase-config.js")
    return url_match.group(1).rstrip("/"), key_match.group(1)


def parse_blog_posts(payload: object, source: str) -> list[BlogPost]:
    if not isinstance(payload, list):
        raise RuntimeError(f"{source} blog post data was not a list")
    posts: list[BlogPost] = []
    for row in payload:
        if not isinstance(row, dict):
            continue
        slug = str(row.get("slug") or "").strip()
        title = str(row.get("title") or "").strip()
        if not slug or not title:
            continue
        if not VALID_SLUG.fullmatch(slug):
            raise RuntimeError(f"Invalid blog slug from {source}: {slug!r}")
        posts.append(
            BlogPost(
                id=int(row.get("id") or 0),
                slug=slug,
                title=title,
                excerpt=str(row.get("excerpt") or "").strip(),
                body=str(row.get("body") or "").strip(),
                cover_image_url=str(row.get("cover_image_url") or "").strip(),
                published_at=str(row.get("published_at") or "").strip(),
                updated_at=str(row.get("updated_at") or "").strip(),
                created_at=str(row.get("created_at") or "").strip(),
            )
        )
    return posts


def fetch_public_blog_posts() -> list[BlogPost]:
    supabase_url, anon_key = read_public_config()
    endpoint = (
        f"{supabase_url}/rest/v1/blog_posts"
        "?select=id,slug,title,excerpt,body,cover_image_url,is_published,published_at,updated_at,created_at"
        "&is_published=eq.true"
        "&order=published_at.desc,id.desc"
    )
    request = Request(
        endpoint,
        headers={
            "apikey": anon_key,
            "Authorization": f"Bearer {anon_key}",
            "Accept": "application/json",
        },
    )
    with urlopen(request, timeout=20) as response:
        payload = json.load(response)
    return parse_blog_posts(payload, "Supabase")


def load_local_blog_posts() -> list[BlogPost]:
    if not LOCAL_BLOG_POSTS_PATH.exists():
        return []

    loader = r"""
const fs = require('fs');
const vm = require('vm');
const source = fs.readFileSync(process.argv[1], 'utf8');
const sandbox = { window: {} };
vm.runInNewContext(source, sandbox, { filename: process.argv[1], timeout: 1000 });
process.stdout.write(JSON.stringify(sandbox.window.__LOCAL_BLOG_POSTS__ || []));
"""
    try:
        result = subprocess.run(
            ["node", "-e", loader, str(LOCAL_BLOG_POSTS_PATH)],
            check=True,
            capture_output=True,
            text=True,
            timeout=10,
        )
    except (FileNotFoundError, subprocess.SubprocessError) as exc:
        raise RuntimeError("Node.js is required to read js/blog-local-posts.js") from exc

    return parse_blog_posts(json.loads(result.stdout), "js/blog-local-posts.js")


def load_published_blog_posts() -> list[BlogPost]:
    by_slug = {post.slug: post for post in load_local_blog_posts()}
    for post in fetch_public_blog_posts():
        by_slug[post.slug] = post

    def sort_key(post: BlogPost) -> tuple[datetime, int]:
        raw = post.published_at or post.updated_at or post.created_at
        try:
            value = datetime.fromisoformat(raw.replace("Z", "+00:00"))
        except ValueError:
            value = datetime.min.replace(tzinfo=timezone.utc)
        if value.tzinfo is None:
            value = value.replace(tzinfo=timezone.utc)
        return value, post.id

    return sorted(by_slug.values(), key=sort_key, reverse=True)


def normalize_asset_url(raw: str) -> str:
    url = str(raw or "").strip()
    if not url:
        return ""
    if re.match(r"^(?:https?:|data:|blob:)", url, re.IGNORECASE):
        return url
    if url.startswith("/"):
        return url
    cleaned = re.sub(r"^(?:\.\.?/)+", "", url)
    return f"/{cleaned.lstrip('/')}"


def absolute_asset_url(raw: str) -> str:
    url = normalize_asset_url(raw)
    if not url:
        return ""
    if re.match(r"^(?:https?:|data:|blob:)", url, re.IGNORECASE):
        return url
    return f"{SITE_ORIGIN}{url}"


def escape_inline(text: str) -> str:
    safe = html.escape(str(text or ""), quote=False)
    safe = safe.replace("\t", "&nbsp;&nbsp;&nbsp;&nbsp;")
    safe = re.sub(r"\+\+([^+\n][^+\n]*?)\+\+", r"<u>\1</u>", safe)
    safe = re.sub(r"\*\*([^*\n][^*\n]*?)\*\*", r"<strong>\1</strong>", safe)
    safe = re.sub(r"(^|[^*])\*([^*\n][^*\n]*?)\*(?!\*)", r"\1<em>\2</em>", safe)
    return safe


def render_body(raw_body: str) -> str:
    raw = str(raw_body or "").replace("\r\n", "\n").replace("\r", "\n").strip()
    if not raw:
        return '<p class="blog-note">No content yet.</p>'

    blocks = [block.strip() for block in re.split(r"\n{2,}", raw) if block.strip()]
    rendered: list[str] = []

    for block in blocks:
        img_match = re.fullmatch(r"!\[(.*?)\]\((.*?)\)", block)
        if img_match:
            alt = html.escape(img_match.group(1).strip() or "Article illustration", quote=True)
            src = html.escape(normalize_asset_url(img_match.group(2)), quote=True)
            if not src:
                continue
            rendered.append(
                f"""
          <figure class="blog-inline-image">
            <img src="{src}" alt="{alt}" loading="lazy">
          </figure>
        """.strip()
            )
            continue

        if block.startswith("## "):
            rendered.append(f"<h2>{escape_inline(block[3:].strip() or 'Section')}</h2>")
            continue

        if block.startswith("### "):
            rendered.append(f"<h3>{escape_inline(block[4:].strip() or 'Subsection')}</h3>")
            continue

        paragraph = "<br>".join(escape_inline(part) for part in block.split("\n"))
        rendered.append(f"<p>{paragraph}</p>")

    return "\n".join(rendered)


def format_date_label(raw: str) -> str:
    if not raw:
        return ""
    try:
        dt = datetime.fromisoformat(raw.replace("Z", "+00:00"))
    except ValueError:
        return raw
    return dt.strftime("%B %-d, %Y")


def iso_to_date(raw: str) -> str:
    if not raw:
        return ""
    try:
        dt = datetime.fromisoformat(raw.replace("Z", "+00:00"))
    except ValueError:
        return ""
    return dt.date().isoformat()


def reading_minutes(post: BlogPost) -> int:
    words = len(
        re.findall(
            r"\S+",
            " ".join([post.title, post.excerpt, post.body]).strip(),
        )
    )
    return max(1, round(words / 220))


def article_url(post: BlogPost) -> str:
    return f"{SITE_ORIGIN}/pages/blog/{post.slug}.html"


def index_url() -> str:
    return f"{SITE_ORIGIN}/pages/blog.html"


def render_head(title: str, description: str, canonical: str, og_type: str, image: str = "") -> str:
    image_tags = ""
    if image:
        image = absolute_asset_url(image)
        image_tags = (
            f'\n  <meta property="og:image" content="{html.escape(image, quote=True)}">'
            f'\n  <meta name="twitter:image" content="{html.escape(image, quote=True)}">'
        )
    return f"""<!DOCTYPE html>
{GENERATED_MARKER}
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <title>{html.escape(title, quote=True)}</title>
  <meta name="description" content="{html.escape(description, quote=True)}">
  <meta name="robots" content="index,follow">
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <link rel="canonical" href="{html.escape(canonical, quote=True)}">
  <meta property="og:site_name" content="Juan R. Reynoso">
  <meta property="og:title" content="{html.escape(title, quote=True)}">
  <meta property="og:description" content="{html.escape(description, quote=True)}">
  <meta property="og:url" content="{html.escape(canonical, quote=True)}">
  <meta property="og:type" content="{html.escape(og_type, quote=True)}">
  <meta name="twitter:card" content="summary_large_image">{image_tags}
  <meta http-equiv="Content-Security-Policy" content="default-src 'self'; base-uri 'self'; object-src 'none'; img-src 'self' data: blob: https://xxrllcpoklgavakmzhnb.supabase.co; media-src 'self' data: blob: https://xxrllcpoklgavakmzhnb.supabase.co; script-src 'self'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com data:; connect-src 'self' https://xxrllcpoklgavakmzhnb.supabase.co; form-action 'self'">
  <meta name="referrer" content="strict-origin-when-cross-origin">
  <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap" rel="stylesheet" />
  <link rel="stylesheet" href="/assets/css/styles.css?v=53" />
"""


def render_site_footer(root_path: str) -> str:
    return f"""
  <footer id="site-footer" data-root-path="{html.escape(root_path, quote=True)}">
    <div class="shell">
      <div class="footer-row">
        <div style="display: flex; align-items: center; gap: 8px;">
          <span>© <span data-footer-year="1">2026</span> Juan R. Reynoso. All rights reserved.</span>
        </div>
        <div class="footer-links">
          <a href="#top">Back to top</a>
        </div>
      </div>
    </div>
  </footer>
"""


def render_blog_index(posts: list[BlogPost]) -> str:
    cards = []
    for post in posts:
        title = html.escape(post.title, quote=True)
        excerpt = html.escape(post.excerpt, quote=False)
        date = format_date_label(post.published_at or post.updated_at or post.created_at)
        image = normalize_asset_url(post.cover_image_url)
        cover_html = ""
        if image:
            cover_html = f"""
            <a class="blog-cover" href="/pages/blog/{html.escape(post.slug, quote=True)}.html">
              <img src="{html.escape(image, quote=True)}" alt="{title}" loading="lazy">
            </a>
"""
        cards.append(
            f"""
          <article class="blog-card">
            {cover_html}
            <div class="blog-card-body">
              {f'<div class="blog-card-meta">{html.escape(date)}</div>' if date else ''}
              <h2 class="blog-card-title"><a href="/pages/blog/{html.escape(post.slug, quote=True)}.html">{title}</a></h2>
              {f'<p class="blog-card-excerpt">{excerpt}</p>' if excerpt else ''}
              <a href="/pages/blog/{html.escape(post.slug, quote=True)}.html" class="blog-card-link">Read →</a>
            </div>
          </article>
"""
        )

    summary = (
        "Practical notes on operations, analytics, and building systems that drive execution."
    )
    schema_posts = []
    for post in posts:
        schema_posts.append(
            {
                "@type": "ListItem",
                "position": len(schema_posts) + 1,
                "url": article_url(post),
                "name": post.title,
            }
        )

    schema_json = json.dumps(
        {
            "@context": "https://schema.org",
            "@type": "CollectionPage",
            "name": "Blog",
            "description": summary,
            "url": index_url(),
            "mainEntity": {
                "@type": "ItemList",
                "itemListElement": schema_posts,
            },
        },
        ensure_ascii=False,
        indent=2,
    )

    cards_html = "".join(cards) or '<div class="blog-empty">No posts published yet.</div>'

    return f"""{render_head('Blog | Juan R. Reynoso', summary, index_url(), 'website')}
</head>
<body class="blog-page">
  <header id="site-header" data-variant="inner" data-active="blog"></header>

  <main id="top">
    <div class="shell">
      <div class="page-intro" style="margin-top: 40px; margin-bottom: 20px;">
        <h1 class="page-title">Blog</h1>
        <p class="page-subtitle" style="max-width: 760px;">
          {html.escape(summary)}
        </p>
      </div>

      <div id="blog-posts-grid" class="blog-grid">
{cards_html}
      </div>

      <div style="height: 60px;"></div>
    </div>
  </main>

{render_site_footer('../')}

  <script src="/js/admin-bootstrap.js?v=6"></script>
  <script src="/js/header.js?v=17"></script>
  <script src="/js/site-shell.js?v=7"></script>
  <script type="application/ld+json">{schema_json.replace('</', '<\\/')}</script>
</body>
</html>
"""


def render_blog_post(post: BlogPost, posts: list[BlogPost]) -> str:
    title = post.title
    excerpt = post.excerpt or ""
    description = excerpt or title
    canonical = article_url(post)
    image = normalize_asset_url(post.cover_image_url)
    body_html = render_body(post.body)
    date_label = format_date_label(post.published_at or post.updated_at or post.created_at)
    date_published = iso_to_date(post.published_at or post.created_at)
    date_modified = iso_to_date(post.updated_at or post.published_at or post.created_at)
    read_minutes = reading_minutes(post)

    related = [p for p in posts if p.slug != post.slug]
    related_html = ""
    if related:
        related_cards = []
        for item in related[:3]:
            related_cards.append(
                f"""
            <article class="blog-related-card">
              <div class="blog-related-meta">{html.escape(format_date_label(item.published_at or item.updated_at or item.created_at))}</div>
              <h3><a href="/pages/blog/{html.escape(item.slug, quote=True)}.html">{html.escape(item.title, quote=True)}</a></h3>
              <p>{html.escape(item.excerpt or '', quote=False)}</p>
            </article>
"""
            )
        related_html = f"""
      <section class="blog-related">
        <div class="blog-related-head">
          <h2>More from the blog</h2>
          <a class="blog-related-all" href="/pages/blog.html">View all posts</a>
        </div>
        <div class="blog-related-grid">
{''.join(related_cards)}
        </div>
      </section>
"""

    schema_json = json.dumps(
        {
            "@context": "https://schema.org",
            "@type": "Article",
            "headline": title,
            "description": description,
            "author": {"@type": "Person", "name": "Juan R. Reynoso"},
            "publisher": {"@type": "Person", "name": "Juan R. Reynoso"},
            "datePublished": date_published,
            "dateModified": date_modified,
            "mainEntityOfPage": canonical,
            "url": canonical,
            "image": absolute_asset_url(image),
        },
        ensure_ascii=False,
        indent=2,
    )

    cover_html = ""
    if image:
        cover_html = f"""
          <figure class="blog-post-media-slot">
            <img src="{html.escape(image, quote=True)}" alt="{html.escape(f'Cover image for {title}', quote=True)}" loading="eager">
          </figure>
"""

    return f"""{render_head(f'{title} | Juan R. Reynoso', description, canonical, 'article', image)}
</head>
<body class="blog-post-page">
  <header id="site-header" data-variant="inner-nested" data-active="blog"></header>

  <main id="top">
    <div class="shell">
      <article class="blog-post-single">
        <div class="blog-post-back-row">
          <a href="/pages/blog.html" class="blog-back-link">← Back to Blog</a>
        </div>

        <header class="blog-post-head">
          <h1 class="blog-post-title">{html.escape(title)}</h1>
          {f'<p class="blog-post-excerpt">{html.escape(excerpt)}</p>' if excerpt else ''}
          <div class="blog-post-meta-row">
            {f'<span class="blog-meta-pill">{html.escape(date_label)}</span>' if date_label else ''}
            <span class="blog-meta-pill">{read_minutes} min read</span>
          </div>
        </header>

{cover_html}
        <div class="blog-prose blog-article-simple">
{body_html}
        </div>
      </article>

{related_html}
    </div>
  </main>

{render_site_footer('../../')}

  <script src="/js/admin-bootstrap.js?v=6"></script>
  <script src="/js/header.js?v=17"></script>
  <script src="/js/site-shell.js?v=7"></script>
  <script type="application/ld+json">{schema_json.replace('</', '<\\/')}</script>
</body>
</html>
"""


def collect_public_urls(posts: list[BlogPost]) -> list[tuple[str, str]]:
    urls: list[tuple[str, str]] = [
        (f"{SITE_ORIGIN}/", "index.html"),
        (f"{SITE_ORIGIN}/pages/about.html", "pages/about.html"),
        (f"{SITE_ORIGIN}/pages/projects.html", "pages/projects.html"),
        (f"{SITE_ORIGIN}/pages/blog.html", "pages/blog.html"),
    ]

    project_dir = ROOT / "pages" / "projects"
    if project_dir.exists():
        for path in sorted(project_dir.glob("*.html")):
            if path.name == "project-template.html":
                continue
            urls.append((f"{SITE_ORIGIN}/pages/projects/{path.name}", f"pages/projects/{path.name}"))

    for post in posts:
        urls.append((article_url(post), f"pages/blog/{post.slug}.html"))

    return urls


def render_sitemap(posts: list[BlogPost]) -> str:
    rows = []
    for url, rel_path in collect_public_urls(posts):
        source_path = ROOT / rel_path
        lastmod = ""
        if source_path.exists():
            lastmod = datetime.fromtimestamp(source_path.stat().st_mtime, tz=timezone.utc).date().isoformat()
        if rel_path.startswith("pages/blog/") and posts:
            post = next((item for item in posts if f"pages/blog/{item.slug}.html" == rel_path), None)
            if post and post.updated_at:
                lastmod = iso_to_date(post.updated_at) or lastmod
        rows.append(
            f"  <url>\n    <loc>{html.escape(url)}</loc>"
            + (f"\n    <lastmod>{html.escape(lastmod)}</lastmod>" if lastmod else "")
            + "\n  </url>"
        )

    return (
        '<?xml version="1.0" encoding="UTF-8"?>\n'
        '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'
        + "\n".join(rows)
        + "\n</urlset>\n"
    )


def render_robots() -> str:
    return f"""User-agent: *
Allow: /
Disallow: /admin/

Sitemap: {SITE_ORIGIN}/sitemap.xml
"""


def write_file(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    content = re.sub(r"[ \t]+(?=\n)", "", content)
    path.write_text(content, encoding="utf-8")


def remove_stale_generated_posts(posts: list[BlogPost]) -> None:
    expected = {f"{post.slug}.html" for post in posts}
    if not BLOG_DETAIL_DIR.exists():
        return
    for path in BLOG_DETAIL_DIR.glob("*.html"):
        if path.name in expected:
            continue
        try:
            source = path.read_text(encoding="utf-8")
        except OSError:
            continue
        if GENERATED_MARKER in source:
            path.unlink()


def main() -> None:
    posts = load_published_blog_posts()

    remove_stale_generated_posts(posts)
    write_file(BLOG_INDEX_PATH, render_blog_index(posts))
    for post in posts:
        write_file(BLOG_DETAIL_DIR / f"{post.slug}.html", render_blog_post(post, posts))
    write_file(ROOT / "sitemap.xml", render_sitemap(posts))
    write_file(ROOT / "robots.txt", render_robots())


if __name__ == "__main__":
    main()
